ALTER TABLE `VisitorLog`
  ADD COLUMN `region` VARCHAR(191) NULL,
  ADD COLUMN `city` VARCHAR(191) NULL,
  ADD COLUMN `visitorId` VARCHAR(191) NULL,
  ADD COLUMN `sessionId` VARCHAR(191) NULL,
  ADD COLUMN `title` VARCHAR(191) NULL,
  ADD COLUMN `durationMs` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `engaged` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `screenWidth` INTEGER NULL,
  ADD COLUMN `screenHeight` INTEGER NULL,
  ADD COLUMN `language` VARCHAR(191) NULL,
  ADD COLUMN `timezone` VARCHAR(191) NULL,
  ADD COLUMN `browser` VARCHAR(191) NULL,
  ADD COLUMN `os` VARCHAR(191) NULL,
  ADD COLUMN `deviceType` VARCHAR(191) NULL,
  ADD COLUMN `utmSource` VARCHAR(191) NULL,
  ADD COLUMN `utmMedium` VARCHAR(191) NULL,
  ADD COLUMN `utmCampaign` VARCHAR(191) NULL,
  ADD COLUMN `utmContent` VARCHAR(191) NULL,
  ADD COLUMN `utmTerm` VARCHAR(191) NULL,
  ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD INDEX `VisitorLog_visitorId_createdAt_idx`(`visitorId`, `createdAt`),
  ADD INDEX `VisitorLog_sessionId_createdAt_idx`(`sessionId`, `createdAt`),
  ADD INDEX `VisitorLog_browser_createdAt_idx`(`browser`, `createdAt`),
  ADD INDEX `VisitorLog_deviceType_createdAt_idx`(`deviceType`, `createdAt`);
